const FETCH_TODO_REQUEST = 'FETCH_TODO_REQUEST'
const FETCH_TODO_SUCCESS = 'FETCH_TODO_SUCCESS'
const FETCH_TODO_FAILURE = 'FETCH_TODO_FAILURE'

const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST'
const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'
const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE'

const CREATE_TODO_REQUEST = 'CREATE_TODO_REQUEST'
const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS'
const CREATE_TODO_FAILURE = 'CREATE_TODO_FAILURE'

const UPDATE_TODO_REQUEST = 'UPDATE_TODO_REQUEST'
const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS'
const UPDATE_TODO_FAILURE = 'UPDATE_TODO_FAILURE'

export {
  FETCH_TODO_REQUEST,
  FETCH_TODO_SUCCESS,
  FETCH_TODO_FAILURE,
  DELETE_TODO_REQUEST,
  DELETE_TODO_SUCCESS,
  DELETE_TODO_FAILURE,
  CREATE_TODO_REQUEST,
  CREATE_TODO_SUCCESS,
  CREATE_TODO_FAILURE,
  UPDATE_TODO_REQUEST,
  UPDATE_TODO_SUCCESS,
  UPDATE_TODO_FAILURE,
}
